### PR TITLE
Fix for Batch Stock Imports & Filter by Date in Grids

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by tom-6x6** [comment]
I can't replicate the sort by date issue @evensis. Can you confirm which Magento/MySQL versions you are running please?

**Comment by evensis** [comment]
Hi Thom,

Not my pull request :-) Must admit I haven't had a problem with the filter by date either.

**Comment by elevateweb** [comment]
Enterprise 1.13.1

**Comment by tom-6x6** [comment]
Apologies @evensis :) 

Thanks @elevateweb - I'll test again on an enterprise 1.13.1 install. Thanks for the PR,  I'll merge in shortly.

**Pull request merged**
