### PR TITLE
Inventory Event and Order Export Validation Feature

### PR DESCRIPTION
**Pull request by evensis**
Few additions with this pull request.

First, I have written a custom caching module for our web store, and I needed a way to invalidate cache on inventory update. So I added an event when an inventory update is processed so that this can be used to invalidate cache.

Furthermore, I have added a feature for when the Magento cron stalls, this happens a few times a year (however at the moment it is far more often due to some buggy community code interacting with Enterprise). Due to having to rely on warehouse staff noticing this (good example - we had a 4 hour gap, with a 100 + orders not being exported in that time), it can lead to orders not going out of the door when they should have.

So in light of this; what this does, is there is a shell script that needs to be added to the server level cron job, which is executed based on the cron expression setup by a system administrator. If it detects more than a predefined level that is set in the orderflow system configuration, then it emails the admin user as well as any other users that are setup in the configuration. There is an on/off configuration for this as well.

This circumvents the Magento cron in the event it stalls, and is extremely useful for us as a business at least, will leave it up to you guys if you would like to merge this pull request but figured it would be handy to other Orderflow uses in the event the cron stalls.

### CODE REVIEW

**Comment by tom-6x6** [comment]
Hi @evensis 

Thanks for the PR.

I definitely the agree with the addition of a custom event as part of the inventory update. There is probably an argument for adding more of these events into the different service endpoints to allow further custom hooks.

I'll have a chat with the guys about frozen cron workaround, and get back to you shortly.

Cheers

Tom

**Comment by evensis** [comment]
Hi guys,

So I have the order export check live, all working dandy, perhaps too well!

We've noticed an issue where a bunch of orders had stacked up, when we tried to export them, in fact they had already been exported and were being reported as duplicates, even though the is_exported column for these were set to false.

For some reason, the module hadn't updated the columns to be set to true. I have noticed this before, but didn't think it was a humungous problem because they seem to trickle down over time. Obviously with this script running ensuring the orders are correctly being exported, the sales_flat_order and sales_flat_order_grid tables need to have the correct data.

The only reason I can think of that would cause this, is perhaps a deadlock on the row. Perhaps, on the duplicate update, the function could be extended to check that the order is is_exported = true, and if not, run an additional function to set the order to true. At least then, orders in this state should set themselves correctly if exported manually.

Although ideally, the issue needs to be found as to why the row isn't being updated with the correct data.

Thanks

**Comment by tom-6x6** [comment]
Hi @evensis 

Thanks for the feedback. The bulk export update is wrapped in a transaction, and therefore row locking should not be a problem here - what is your current batch limit for each order export?

Can you confirm whether the failed orders are sequential or random across your order set? A sequential sequence would probably indicate some kind of deadlocking issue as the complete transaction should then role back.

Another option would be to set the export column to true for orders that are marked as duplicates by OF - although this may cause problems for genuine duplicate orders - leaving them unflagged for attention.

It'd be great to get to a position where we can replicate this. I'm still awaiting feedback on your PR atm, but should be a position to merge shortly.

Cheers

Tom

**Comment by evensis** [comment]
Hi Tom,

Thanks for coming back. The current export limit for orders is 100.

The orders that caused the major stack up last night, all occurred between midnight and 1:36am. This is outside of our full reindex time as well (i know product price index causes massive problems with the sales order tables, so not that! Well at least has enough to do with it to cause deadlocks while it runs when creating an order) which runs at 2:30am. So it's not going to be sequential, but rather random which makes it slightly more tricky as to where the issue came from.

So Orderflow has the capability to see two orders on two different order numbers that have the same details and order lines and treat them as duplicates? Wasn't aware of this! Ideally Orderflow should send something back saying order: foo and order: bar are the same, rather than just responding with a flat duplicate. We know in Magento we can't have the same increment id as it would fail on an integrity constraint violation, so we can safely assume that a duplicate wouldn't be the result of this. Think the feature is a bit limited in its response in order to properly differentiate between orders already sent down and actual duplicate orders. Might be worth throwing at Charlie if this is the case, and perhaps this can be added to their road map to seperate this out.

Thanks,

Adam

**Comment by tom-6x6** [comment]
Hi @evensis 

I'm pretty sure OF relies on the order increment ID to identify duplicates, and not the order information - I'll pass this question onto Charlie to verify.

If the problem is not affecting a complete batch of orders, then I wouldn't expect this to be a deadlock issue as the complete transaction should roll back.

Can you verify that the stuck orders are actually visible in the OF console (I assume they are as you are receiving a duplicate response), and at what time were they exported in comparison to the duplicate failure message in Magento.

Cheers

Tom

**Comment by evensis** [comment]
Hi Tom,

Is the duplicate order check really necessary then? Just did a show create table on sales_order_flat and definitely has a unique key reference on increment_id:

UNIQUE KEY `UNQ_SALES_FLAT_ORDER_INCREMENT_ID` (`increment_id`),

The database table wouldn't allow it to happen, the problem would show in Magento before it got to Orderflow.

I've exported the problematic errors to a csv, and have 19 examples, heres one for example:

100264227 - Purchased: 21 Jul 2015 01:31:49
It was created on orderflow: 21 July, 2015 01:43:23 

So definitely visible, and was created just over 10 minutes later. It obviously sent it down, and then didn't update the sales_flat_order table for some reason or another. When sending it down again manually it was throwing duplicate error messages.

If you need any more information let me know.

Thanks,

Adam

**Comment by tom-6x6** [comment]
Hi @evensis 

It was one of the original requirements from RTD to handle duplicates in this way. However, we are probably safe to mark both successful, and duplicate exports as exported. I'll put this to @charliearmor, and get back to you shortly.

Additionally, I'll attempt to replicate the issue, which will allow us to solve the problem rather than rely on the work around detailed above.

Cheers

Tom

**Pull request closed without merging**
